DROP VIEW OldCompanies,
    OldCompaniesCounter,
    IndustrialCountry,
    CompanyInIndustrialCountries,
    HighestStocksOfCompaniesInIndustrialCountries,
    HighestStocksOfCompanies,
    HighestPerLocation,
    Comparison,
    AllSymbols,
    ImprovedCompany,
    ImprovedCompanyWithSector,
    NumberOfImprovedCompaniesInSector,
    GlamorousCompany,
    MaxDate,
    MaxPrice,
    MinDate,
    MinPrice,
    ProfitPercentage;
